/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './file-input.module';
import * as i2 from '@angular/forms';
export const FileInputModuleNgFactory:i0.NgModuleFactory<i1.FileInputModule> = i0.ɵcmf(i1.FileInputModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.ɵi,i2.ɵi,([] as any[])),i0.ɵmpd(4608,i2.FormBuilder,i2.FormBuilder,([] as any[])),
          i0.ɵmpd(512,i2.ɵba,i2.ɵba,([] as any[])),i0.ɵmpd(512,i2.FormsModule,i2.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i2.ReactiveFormsModule,i2.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i1.FileInputModule,i1.FileInputModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvbi9Qcm9qZWN0cy9GaWxlSW5wdXREaXJlY3RpdmUvZmlsZS1pbnB1dC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvam9uL1Byb2plY3RzL0ZpbGVJbnB1dERpcmVjdGl2ZS9maWxlLWlucHV0Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
